### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by mzhukovs** [Gandi/gandi-pyramid-prometheus#5]
This lib appears to be exactly what I was looking for - thank you for building this @mardiros . Question - can you please point me to how to any docs/examples on how to put it to use in an existing pyramid backend project and any setup on the prometheus/grafana side? That would be very helpful and much appreciated.

**Comment by Themimitoof** [comment]
Hi @mzhukovs!

The simplest way to use this library on your project is by including the lib via the Configurator with `config.include("gandi_pyramid_prometheus")` or via the ini file:

```ini
pyramid.includes =
    gandi_pyramid_prometheus
```

That's pretty much you need to do but you can also specify your own metrics with `prometheus_client`. In term of customization of this module, you can configure the route (by default is `/metrics`) and enable multiproc. Here's the name of the settings:

 - prometheus.use_multiproc (default: `false`, if you set to `true`, ensure you have set the env variable `PROMETHEUS_MULTIPROC_DIR`. For more info: https://github.com/prometheus/client_python#multiprocess-mode-eg-gunicorn)
 - prometheus.metrics_path_info (default: `/metrics`)

Here a simple example to specify custom metrics:

```python
import logging

import pkg_resources
from prometheus_client import Gauge

log = logging.getLogger(__name__)
__version__ = pkg_resources.get_distribution("my_pyramid_app").version

version_info = {"version": __version__}

app_info = Gauge(
    "api_xxx_info",
    "API XXX Information",
    labelnames=list(version_info.keys()),
    multiprocess_mode="max",
)
app_info.labels(**version_info).set(1)

messagebus_message_count = Counter(
    "xxx_messagebus_message_to_process_count",
    "Count the number of messages to process in the messagebus",
    ["message_type"],
)
```

This module expose two metrics (https://github.com/Gandi/gandi-pyramid-prometheus/blob/master/gandi_pyramid_prometheus/prometheus.py):
 - `pyramid_request_ingress`: Gauge
 - `pyramid_request`: Histogram

I'm gonna create a PR to add all the information in the README for other developers ;)

Let us know if you need more information!

**Comment by mzhukovs** [comment]
Thank you very much , that's very helpful
